spring:
  application:
    name: InternLink
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/internlink
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
